### ISSUE TITLE
Callstats Package in tandem with Amazon Connect CCP Call Centers

### ISSUE THREAD

**Issue by jordanbaucke** [callstats-io/amazon-connect-reference-dialer#27]
I have been asked to install this package into a few Salesforce organizations that are already running Amazon Connect CCP Adapter (which includes it's own configurable Salesforce _Call Center_ records.)

Is it possible to use this managed package in tandem with the Amazon Connect CCP Adapter Call Center (where we had added our direct Amazon Connect CCP URL) 

When I install the managed package I have a new CallCenter which the [README](https://github.com/callstats-io/amazon-connect-reference-dialer/blob/master/README.salesforce.md) seems to indicate is where I should configure and add my call-center users.

I have added my _**Amazon Connect CCP URL here**_, but as _my users are already configured to another call-center_ (and I do not believe they can be aligned to more than one) **_is it possible to use the CallStats.IO package and the Amazon Connect CCP Adapter at the same time??_** (which includes metadata variables from Amazon Connect, and related record screen/activity pops). 

Thanks

**Comment by LongHDinh** [comment]
Hi @jordanbaucke ,
 It is not possible to use the callstats.io package with the Amazon Connect CCP Adapter since you’ll need the callstats integration settings in our callstats Adapter to use all our dialer's features.
 Unfortunately you will have to reassign your users to our Call Center and set their Amazon Connect CCP URL as well as callstats appID and appSecret there.

**Comment by jordanbaucke** [comment]
@LongHDinh Thank you for getting back to me so quickly! I will keep this in mind.

Jordan
